"""Build data/plant_data.json from embedded CSV rows."""
import json
import os

# index, disease_name, description, prevention, image_url
DISEASES = [
(0,"Apple : Scab","Apple scab is the most common disease of apple and crabapple trees in Minnesota. Scab is caused by a fungus that infects both leaves and fruit. Scabby fruit are often unfit for eating. Infected leaves have olive green to brown spots. Leaves with many leaf spots turn yellow and fall off early. Leaf loss weakens the tree when it occurs many years in a row. Planting disease resistant varieties is the best way to manage scab.","Choose resistant varieties when possible. Rake under trees and destroy infected leaves to reduce the number of fungal spores available to start the disease cycle over again next spring. Water in the evening or early morning hours (avoid overhead irrigation) to give the leaves time to dry out before infection can occur. Spread a 3- to 6-inch layer of compost under trees, keeping it away from the trunk, to cover soil and prevent splash dispersal of the fungal spores. For best control, spray liquid copper soap early, two weeks before symptoms normally appear.","https://extension.umn.edu/sites/extension.umn.edu/files/apple-scab-1.jpg"),
(1,"Apple : Black Rot","Leaf symptoms first occur early in the spring when the leaves are unfolding. They appear as small, purple specks on the upper surface of the leaves that enlarge into circular lesions. The margin of the lesions remains purple, while the center turns tan to brown. In a few weeks, secondary enlargement of these leaf spots occurs. Heavily infected leaves become chlorotic and defoliation occurs.","Remove the cankers by pruning at least 15 inches below the end and burn or bury them. Also take preventative care with new season prunings and burn them, too. You are better off pruning during the dormant season. Using a copper-based fungicide will protect against both black rot and fire blight.","http://www.omafra.gov.on.ca/english/crops/facts/blackrotf1.jpg"),
(2,"Apple : Cedar rust","Cedar apple rust is a fungal disease that requires juniper plants to complete its complicated two year life-cycle. Spores overwinter on juniper and infect apple trees in spring.","Choose resistant cultivars when available. Rake up and dispose of fallen leaves. Remove galls from infected junipers. Apply preventative fungicides labeled for use on apples weekly starting at bud break.","https://www.planetnatural.com/wp-content/uploads/2012/12/apple-rust.jpg"),
(3,"Apple : Healthy","As with most fruit, apples produce best when grown in full sun. Apple trees need well-drained soil but should retain some moisture.","Apples are nutritious, may aid weight loss and heart health, and provide antioxidants and fiber.","https://previews.123rf.com/images/msnobody/msnobody1508/msnobody150800002/43698436-red-apple-on-a-branch.jpg"),
(4,"Background Without Leaves","There is no leaf in the given image, please reupload image with leaf.","Please upload a clear photo of a plant leaf for analysis.","https://cdn.onlinewebfonts.com/svg/img_332817.png"),
(5,"Blueberry : Healthy","Blueberries are low in calories but high in nutrients and antioxidants.","Deep, low pH mulch like peat moss conserves water. Water routinely during growing season.","https://image.shutterstock.com/image-photo/blueberry-leaf-collection-isolated-on-260nw-308491814.jpg"),
(6,"Cherry : Powdery Mildew","Initial symptoms are light powdery patches on young leaves. Powdery mildews do not need free water to germinate.","Disinfect pruning tools, prune out diseased portions immediately, apply fungicides to protect remaining leaves.","http://treefruit.wsu.edu/wp-content/uploads/2017/05/Fig1.png"),
(7,"Cherry : Healthy","Cherry trees need regular pruning, fertilizing, and spraying to stay healthy and productive.","Packed with nutrients and antioxidants. May benefit heart health and exercise recovery.","https://previews.123rf.com/images/annafrby/annafrby1907/annafrby190700078/127086189-cherry-on-branch.jpg"),
(8,"Corn : Cercospora Leaf Spot | Gray Leaf Spot","Gray leaf spot on corn is caused by Cercospora zeae-maydis. The disease has increased in importance in many corn-growing regions.","Irrigate deeply but infrequently. Avoid post-emergent weed killers while disease is active. Improve air circulation on lawn areas.","https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Gray_leaf_spot_Cercospora_zeae-maydis_5465607.png/330px-Gray_leaf_spot_Cercospora_zeae-maydis_5465607.png"),
(9,"Corn : Common Rust","Dark reddish-brown pustules scattered over both upper and lower surfaces of corn leaves.","Plant corn with resistance to rust where possible. Spray with fungicide if infection appears.","https://ohioline.osu.edu/sites/ohioline/files/imce/Plant_Pathology/PLNTPTH-CER-02_Figure_1.png"),
(10,"Corn : Northern Leaf Blight","Long elliptical gray-green lesions that turn pale gray or tan. Caused by Setosphaeria turcica.","Fungicide applications at disease onset protect yield. Apply when disease first appears, repeat per label.","https://crop-protection-network.s3.amazonaws.com/articles/NLB-Daren-Mueller-02.jpg"),
(11,"Corn : Healthy","Corn prefers warm temperatures and consistent moisture without waterlogging.","Corn provides fiber, B vitamins, and essential minerals such as zinc and manganese.","https://c8.alamy.com/comp/A85TR2/young-healthy-green-leaves-of-corn-maize-plant-A85TR2.jpg"),
(12,"Grape : Black Rot","Grape black rot is a fungal disease caused by Guignardia bidwellii. Can cause complete crop loss in warm humid climates.","Mancozeb fungicides are effective. Nova (myclobutanil) is also used for black rot control.","https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Guignardia_bidwellii_08.jpg/330px-Guignardia_bidwellii_08.jpg"),
(13,"Grape : Esca | Black Measles","Grapevine measles (esca) has long plagued grape growers. Fruit may develop spots and acrid taste.","Remove infected berries, leaves and wood and destroy them. Protect prune wounds with sealant or suitable fungicides.","https://www.researchgate.net/profile/Laura-Mugnai/publication/43161073/figure/fig1/AS:340404659605512@1458170203496/Symptoms-associated-with-esca-of-grapevine.jpg"),
(14,"Grape : Leaf Blight | Isariopsis Leaf Spot","Pale yellow-green lesions which gradually turn brown. Frequently confused with powdery mildew.","Apply dormant sprays. Improve canopy airflow. Use protectant and systemic fungicides. Scout regularly.","https://www.goodfruit.com/wp-content/uploads/Black-rot-lesions-on-leaves-indicate-potential-for-fruit-infection-1-feat2.jpg"),
(15,"Grape : Healthy","Water only at root zone. Avoid wetting foliage. Reduce watering young vines in fall.","High in vitamins C and K. Contains antioxidants that may protect against chronic diseases.","https://images.indianexpress.com/2021/02/grapes-1200.jpg"),
(16,"Orange : Haunglongbing | Citrus Greening","Citrus greening causes yellowing of veins, blotchy mottling, dieback, and bitter misshapen fruit.","Control Asian citrus psyllid vectors. Spray with appropriate insecticide and follow with copper fungicide if needed.","https://www.universityofcalifornia.edu/sites/default/files/CitrusGreening.jpg"),
(17,"Peach : Bacterial Spot","Bacterial spot caused by Xanthomonas campestris pv. pruni. Causes fruit spots, leaf spots, and twig cankers. Severe defoliation reduces vigor.","Do not confuse with peach scab. Remove badly infected plant parts. Use copper-based sprays during dormancy.","https://www.gardeningknowhow.com/wp-content/uploads/2016/07/bacterial-spot-peach.jpg"),
(18,"Peach : Healthy","Peach trees grow in USDA Zones 5-8. Need regular pruning, fertilizing, and mulching.","Packed with nutrients and antioxidants. May aid digestion and heart health.","https://www.tasteofhome.com/wp-content/uploads/2019/06/peaches-shutterstock_297863489-1.jpg"),
(19,"Pepper bell : Bacterial Spot","Small water-soaked spots on leaves that enlarge with gray-tan centers. Spread by splashing rain.","Use resistant varieties and disease-free seed. Treat seeds with bleach solution. Use copper fungicides preventively.","https://extension.umd.edu/sites/default/files/_images/programs/grow_it_eat_it/diseases/BacterialLeafSpot/bacterial_leaf_spot_pepper_plant_l.jpg"),
(20,"Pepper bell : Healthy","Keep bell peppers well-watered with consistent moisture especially during fruit set.","Excellent source of vitamins A and C, potassium, fiber, folate, and iron.","https://www.healthbenefitstimes.com/9/gallery/bell-peppers/Bell-pepper-leaves.jpg"),
(21,"Potato : Early Blight","Small dark-brown to black spots on older leaves. Enlarges under favorable conditions.","Plant resistant varieties. Avoid overhead irrigation. Allow foliage to dry quickly.","https://www.ag.ndsu.edu/publications/crops/early-blight-in-potato/figure-1-opt.jpeg"),
(22,"Potato : Late Blight","Water-soaked spots that expand rapidly in cool moist weather. Caused by Phytophthora infestans.","Prophylactic mancozeb followed by systemic fungicides at disease onset.","https://www.ag.ndsu.edu/publications/crops/late-blight-in-potato/figure-2-opt.jpeg"),
(23,"Potato : Healthy","Keep planting beds moist until emergence. Water regularly during flowering and pod formation.","High in fiber and antioxidants. Naturally gluten-free and filling.","https://www.garden.eco/wp-content/uploads/2018/06/can-you-eat-potato-leaves.jpg"),
(24,"Raspberry : Healthy","Water one inch per week. Remove suckers away from rows to maintain vigor.","Provide potassium and omega-3 fatty acids. Manganese helps regulate blood sugar.","https://www.gardeningknowhow.com/wp-content/uploads/2009/04/raspberry.jpg"),
(25,"Soybean : Healthy","Keep beds evenly moist until emergence. Mulch when soil warms above 16C.","High in fiber and protein, low in saturated fat, good source of omega-3.","https://upload.wikimedia.org/wikipedia/commons/a/ac/Soybean_leaves.jpg"),
(26,"Squash : Powdery Mildew","White powdery spots on leaves that expand into blotches. Weakens plants and reduces fruit.","Improve spacing and airflow. Baking soda spray can help control mildew spores.","https://extension.umn.edu/sites/extension.umn.edu/files/styles/caption_medium/public/powdery-mildew-2.jpg"),
(27,"Strawberry : Leaf Scorch","Dark purple spots resembling tar drops. Leaves turn brown and curl giving scorched appearance.","Sanitation is key: remove infected debris. Establish new transplants regularly.","https://content.ces.ncsu.edu/media/images/17531_IMG_2126.JPG"),
(28,"Strawberry : Healthy","Sunny location, daily watering, good drainage, balanced fertilizer.","High in antioxidants and vitamin C. Low calorie and heart-healthy.","https://www.canr.msu.edu/uploads/images/7-12-11-MARK-plhstrw4.jpg"),
(29,"Tomato : Bacterial Spot","Small water-soaked circular leaf spots. Severe cases cause leaf yellowing and fruit lesions.","Use pathogen-free seed. Avoid overhead watering. Copper sprays during warm wet periods.","https://www.growingproduce.com/wp-content/uploads/2019/08/bacterial_spot_tomato.jpg"),
(30,"Tomato : Early Blight","Very common tomato disease affecting leaves, fruits and stems. Can limit yield severely.","Improve air circulation. Disinfect pruners. Copper fungicides early or when disease appears.","https://extension.umn.edu/sites/extension.umn.edu/files/styles/large/public/early-blight-leaf-tomato.jpg"),
(31,"Tomato : Late Blight","Potentially devastating disease spreading quickly in wet weather. Caused by Phytophthora infestans.","Clean up debris. Inspect plants twice weekly. Mancozeb or chlorothalonil protectants.","https://www.canr.msu.edu/contentAsset/image/e97d1ef0-5b55-49b0-ab4e-c57dcbeca65e/fileAsset/filter/Resize,Jpeg/resize_w/750/jpeg_q/80"),
(32,"Tomato : Leaf Mold","Fungal disease in high humidity. Yellow spots on upper leaf surface with olive spores below.","Cover all above-soil areas when spraying. Calcium chloride or organic fungicide options available.","https://www.gardeningknowhow.com/wp-content/uploads/2018/04/tomato-leaf-mold-400x300.jpg"),
(33,"Tomato : Septoria Leaf Spot","Circular spots with dark margins and tan centers. Many spots per leaf. Spreads upward on plant.","Remove diseased leaves. Mulch base. Avoid overhead watering. Crop rotation 1-2 years.","https://www.missouribotanicalgarden.org/portals/0/Gardening/Gardening%20Help/images/Pests/Septoria_Leaf_Spot_of_Tomato187.jpg"),
(34,"Tomato : Spider Mites | Two-Spotted Spider Mite","Common mite on tomato and other crops. Favored by excess nitrogen and dry dusty conditions.","Avoid weedy fields. Do not over-fertilize. Overhead irrigation can reduce populations.","https://entomology.ca.uky.edu/files/styles/panopoly_image_original/public/310a.jpg"),
(35,"Tomato : Target Spot","Irregular spots with concentric rings on leaves. Spreads fast in windy wet weather.","Do not plant near infected papaya. Remove lower leaves when disease appears. Crop rotation.","https://barmac.com.au/wp-content/uploads/sites/3/2016/01/Target-Spot-Tomato1.jpg"),
(36,"Tomato : Yellow Leaf Curl Virus","TYLCV transmitted by whitefly Bemisia tabaci. Causes stunting and yield losses worldwide.","Virus-free transplants. Whitefly control with approved insecticides. Rotate chemicals to avoid resistance.","https://gd.eppo.int/media/data/taxon/T/TYLCV0/pics/1024x0/10609.jpg"),
(37,"Tomato : Mosaic Virus","Mottled light and dark green leaves, stunted growth, malformed leaves on tomatoes.","Certified disease-free seed. Soak seeds in 10% trisodium phosphate 15 min. Sanitize tools.","http://ucanr.edu/blogs/dirt/blogfiles/71403_original.jpg"),
(38,"Tomato : Healthy","Fertilize before planting. Provide lots of light. Water regularly and mulch after soil warms.","Major source of lycopene, vitamin C, potassium, folate, and vitamin K.","https://cdn8.dissolve.com/p/D869_27_632/D869_27_632_1200.jpg"),
]

SUPPLEMENTS = [
(0,"Katyayani Prozol Propiconazole 25% EC Systematic Fungicide","https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRfq9MLrPL9tFkuFbGb98fMGDdl67v4I2iDLYCVprdsdGaXURCl9UNEr8v_65X1hKrYF5NjSvB01HOGexg-3CJxjkVSu9zPNJ2AunP09vPa0gjEILskTILx&usqp=CAE","https://agribegri.com/products/buy-propiconazole--25-ec-systematic-fungicide-online-.php"),
(1,"Magic FungiX For Fungal disease","https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcTZZH2SUe7Hufpd49iFoF_04c96J-fZeywsYQXDb0gFerGOYyL7xPBxLN05LIx6s36u6C_qMvtescsDbrTEzniJp0yhfEsvJoTCMD7FDnI&usqp=CAE","https://agribegri.com/products/buy-fungicide-online-india--organic-fungicide--yield-enhancer.php"),
(2,"Katyayani All in 1 Organic Fungicide","https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcT2JQ-fAdtrzzmkSespqEpKwop3BnWntsLioVSgjy79mpxQVPSqoD4v9yfL0mtiFJvFnPqeE7EcefadhdEpc9uUTCZbROwOPsklL_XDMSLTpxOGvIcBMMFiBQ&usqp=CAE","https://agribegri.com/products/buy-organic-fungicide-all-in-1-online--organic-fungicide-.php"),
(3,"Tapti Booster Organic Fertilizer","https://rukminim1.flixcart.com/image/416/416/kc6jyq80/soil-manure/6/y/v/500-tapti-booster-500-ml-green-yantra-original-imaftd6rrgfhvshc.jpeg?q=70","https://agribegri.com/products/tapti-booster-500-ml--organic-fertilizer-online-in-india.php"),
(4,"","","",""),
(5,"GreenStix Fertilizer","https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSW_S8Mrnq0lLnXWCSPPlONkrPbkB8C3Gy9613OGD0ZaejmP5UNRf8LFnXUYJTM64BC1VYLYcYSbSSv-qVTV15RzDJZipvzsikme8oHSEtVX_ZKDiUQpnbHPQ&usqp=CAE","https://lazygardener.in/products/greenstix"),
(6,"ROM Mildew Clean","https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcSeHlqcksdF25o8mv-fYxNOrfJkp4Ov2hgVf01w2aCed1WbyL604ubLtPAlB7rfNoHRtxbTljQvA7P3VRh8LM0XndFHWDqvC4kC4w-DLQiknnS3vRzAxTpP&usqp=CAE","https://agribegri.com/products/rom-mildew-clean-1-kg--price-of-organic-fungicide-online-.php"),
(7,"Plantic Organic BloomDrop Liquid Plant Food","https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSpHb-xEa2rTSIEf5QtLMbax4zvRsTzD4kAwQ9Rcwr3AbDDQxUhmMmPJBVGLCAvczXrXAqwWKN-rReHwSR-XSGlsJRLvZOKRXHV-54uLhU_6EIuBq5BHXaAwg&usqp=CAE","https://plantic.in/products/organic-bloomdrop"),
(8,"ANTRACOL FUNGICIDE","https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcTm0wIanaB9OdUkuH9IJ-bHG_qyungwi2lWnmkFmze9VFU1yeSuRO3wImAhPfEJwuBZXPSEf5QwZhieERwrlE5H7lg_8bvf&usqp=CAE","https://www.bighaat.com/products/antracol"),
(9,"3 STAR M45 Mancozeb 75% WP Contact Fungicide","https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcT86avIdiTsKNdgo0Uss9r2tkn9pcx6VCGHeaubXDiR0u_fqqyXomgc1BBviREao7BM_eQiR6tbLCzUxG5VzS4du5DgwBVbtwSLuTEexpI&usqp=CAE","https://agribegri.com/products/buy-online-3-star-m45-mancozeb-75-wp.php"),
(10,"QUIT (Carbendazim 12% + Mancozeb 63% WP)","https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRO2FK6IsSuUuQQ0ehzVKIsEdgjCGbMq2nBmOsUp38ajgm8dPwR9MvTBL9_PFRZVRkbtiAzdwP8lwGlrR1c7axKHE6VALk6l3X4Snu9HWFCKpVCFYly65Bs&usqp=CAE","https://agribegri.com/products/buy-carbendazim-12--mancozeb-63-online--buy-fungicide-online.php"),
(11,"Biomass Lab Sampoorn Fasal Ahaar","https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRC_8hhC12Kbw0e0w-afXO9kzWJHG1LchaIa66xnIpU6OmZLnY3OzCrRd2ilBS9bSjI9jQI0hJ6Z20SUk7nf7uCukqv77aTun147K5g2Ec&usqp=CAE","https://www.flipkart.com/biomass-lab-sampoorn-fasal-ahaar-multipurpose-organic-fertilizer-plant-food-1-kg-fertilizer-manure/p/itm69c56f2e19c6a"),
(12,"Southern Ag Captan 50% WP Fungicide","https://images-na.ssl-images-amazon.com/images/I/51s1IbUD-qL.jpg","https://www.cart2india.com/beneficial-insects/southern-ag-captan-50-wp-fungicide-8-oz/00000000004336428163"),
(13,"ALIETTE FUNGICIDE","https://farmagritech.com/wp-content/uploads/2020/03/ALIETTE.png","https://farmagritech.com/product/aliette-fungicide/"),
(14,"Tebulur Tebuconazole 10% + Sulphur 65% WG","https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQPzI0SnMtb60x2D1gGkRHsvD1j7NRl8Y7pjuIyuyrTxdpvUOpci7NxHWxt4Gfn3ETrCrgWKvGPH-jmbboE2vi4b4MiTq3kZKMdHFUSctUmXcH9ZRed0j4-&usqp=CAE","https://agribegri.com/products/buy-tebuconazole-10--sulphur-65-wg-online--online-agro-store.php"),
(15,"Sansar Green Grapes Fertilizer","https://rukminim1.flixcart.com/image/416/416/k51cpe80/soil-manure/4/m/h/400-grapes-fertilizer-sansar-green-original-imafntdujntbdner.jpeg?q=70","https://www.flipkart.com/sansar-green-grapes-fertilizer/p/itm90f06136b50c7"),
(16,"Green Dews CITRUS PLANT FOOD Fertilizer","https://rukminim1.flixcart.com/image/416/416/ju79hu80/soil-manure/x/m/b/400-citrus-plant-food-green-dews-original-imaffbxhn3rz8k5p.jpeg?q=70","https://www.flipkart.com/green-dews-citrus-plant-food-fertilizer/p/itmffde2heg7hkq2"),
(17,"SCORE FUNGICIDE","https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQ5shxq773t5Lmux-hhShKezjR64Af41W6NdhsDMXI-dNSAVvfY45rb5iHxMaqZXBdtFnfuiIcN8PdQ06YcYZi3gq6Uow-j&usqp=CAE","https://www.bighaat.com/products/score-fungicide"),
(18,"Jeevamrut (Plant Growth Tonic)","https://cdn.shopify.com/s/files/1/0047/9730/0847/products/nurserylive-fertilizer-jeevamrut-plant-growth-tonic-500-ml-for-garden_jpg_600x600.jpg?v=1607402323","https://nurserylive.com/products/jeevamrut-plant-growth-tonic-250-ml-for-garden"),
(19,"Systemic Fungicide (Domark) Tetraconazole 3.8%","https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQNEP3gEC77FdOUBy_xUgIbq7UU_N2TX1zRwCFvtl02Kz5-a6X2ZhXPAhf9y0kLieGR2VTVarUnZP_JMs0kFtEw-LqJwVSMHsjGP4Bz9scPPIB6NCLtcD7JNA&usqp=CAE","https://agribegri.com/products/buy-systemic-fungicide-online--tetraconazole-38--domark-.php"),
(20,"Casa De Amor Organic Potash Fertilizer","https://cdn.shopify.com/s/files/1/1489/8850/products/Organic_Potash-1_869x869.jpg?v=1583399466","https://www.casagardenshop.com/products/organic-potash-fertilizer-for-gardening-improves-size-of-flowers-fruits-and-vegetables-by-casa-de-amor-1-kg-1"),
(21,"Parin Herbal Fungicides (With Turmeric Extract)","https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcQzAaBb9Tc2B0iXiYc08qD2WM4vjAz4TZHI6qwj-D7nck2bbtYQUnnODSqPSK_Vz5NR1Am8aRbc2Rd0anzqgVKWq-0OlZ6wkjE-3x0jXihQ9F0kO8nJu7FT&usqp=CAE","https://agribegri.com/products/buy-herbal-fungicide-online-india--buy-pesticides-online.php"),
(22,"Syngenta Ridomil gold Fungicide","https://krushikendra.com/image/cache/catalog/syngenta/RIDOMIL-GOLD-800x800.jpg","https://krushikendra.com/Buy-Syngenta-Ridomil-gold-Fungicide-250%20gram"),
(23,"Saosis Fertilizer for potato","https://rukminim1.flixcart.com/image/416/416/kfvfwy80/soil-manure/6/p/g/30-fertilizer-for-potato-saosis-original-imafw8b3sgcyrhh4.jpeg?q=70","https://www.flipkart.com/saosis-fertilizer-potato/p/itmc40dfbfcd49f7"),
(24,"Karen's Naturals, Organic Just Raspberries","https://s3.images-iherb.com/jte/jte29001/v/6.jpg","https://in.iherb.com/pr/Karen-s-Naturals-Organic-Just-Raspberries-1-5-oz-42-g/37730"),
(25,"Max Crop Liquid Fertilizer","https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcRyFZFHGj1Wi0fabSOYVadCnsg8UdvhpKOHI6gxmItDLmz7RdC67HFFNyU7PYyD6SnlgXOs31yW_8-YWJKOeal7K4UQ3lAIxef-4x350ac&usqp=CAE","https://agribegri.com/products/max-crop-1-litre.php"),
(26,"No powdery mildew 1 quart","https://cdn.shopify.com/s/files/1/1667/9587/products/415B_2BfINScL.jpg?v=1536320654","https://kiron.co.in/products/B0068WMLE2"),
(27,"Greatindos Premium Quality All in 1 Organic Fungicide","https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcSV3dLQAuhGWWsZSX3Ray15J_uSeFgSo7oLE0G2BxPFSwVNnOUY7VsBbLzDbw_mzUw3ZFLaF4kPWPyzatefP2bnSZwEbwrYnGGYgEl8rS6XWmwRnloOWnwy&usqp=CAE","https://agribegri.com/products/buy-organic-fungicide-online--organic-fungicide-with-best-rate-.php"),
(28,"SWISS GREEN ORGANIC PLANT GROWTH PROMOTER STRAWBERRY","https://rukminim1.flixcart.com/image/416/416/k2urhjk0/soil-manure/q/y/d/500-organic-plant-growth-promoter-strawberry-swiss-green-original-imafm3vx8mzyhxzg.jpeg?q=70","https://www.flipkart.com/swiss-green-organic-plant-growth-promoter-strawberry-fertilizer-manure/p/itmcaf7955b802fa"),
(29,"CUREAL Best Fungicide & Bactericide","https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRKHQh4EwbE0ksZ_RTOhsGtvTO68zllR9djrYvUrZ-DO6FYo2kYpmyFL8UgaK6aiHJuUWbkax_uhcxMpGfwSHa2CKWqaIZnFp1vIRbGkrZhtGv-Zq-72y61&usqp=CAE","https://agribegri.com/products/cureal---best-fungicide--bactericide-zinc-based-250-ml.php"),
(30,"NATIVO FUNGICIDE","https://farmagritech.com/wp-content/uploads/2019/11/F-Nativo-3.jpg","https://farmagritech.com/product/nativo-fungicide/"),
(31,"ACROBAT FUNGICIDE","https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRpQmIM9QZkFI43PPlHVFaSlGdrdMP8LFHXAo9b_OGOQCi3R6G-SsqnCXFR4CU9bVAcyuBGTrQRAkRrU9fm-1TGeXg9PrsB&usqp=CAE","https://www.bighaat.com/products/acrobat-fungicide"),
(32,"Virus Special (Immuno + Enviro 1 ltr)","https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQfgH6lswqhV2hUhqZwEfgQBU1eUP1GCvETxg_a3JFOERS2tc80k8gNMbHM_XxReblck1T7tR95X8Qojdj1k0yAyvhmCZHvkFWaT_L-a8ofElEXerVJqvsF&usqp=CAE","https://agribegri.com/products/virus-special-enviroimmuno-1-litre.php"),
(33,"Roko Fungicide","https://farmagritech.com/wp-content/uploads/2020/05/roko-insecticide.jpg","https://farmagritech.com/product/roko-fungicide/"),
(34,"OMITE INSECTICIDE","https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcQxe-M4vyRx94TlpTOw6tlzvagjvaTRCWRLoKd58JML7T3rSV8GJK67YjxIiR-PHL02DL2CHsHPLzExBf6uq7BqxcLPxgmh9w&usqp=CAE","https://www.bighaat.com/products/omite-insecticide"),
(35,"Propi Propineb 70% WP Fungicide","https://rukminim1.flixcart.com/image/416/416/k3xcdjk0/soil-manure/y/f/j/100-propineb-70-wp-fungicide-for-plants-diesese-control-propi-original-imafmxg3jghhdyt6.jpeg?q=70","https://www.flipkart.com/propi-propineb-70-wp-fungicide-plants-diesese-control-pesticide/p/itm9db96656402f8"),
(36,"Syngenta Amistor Top Fungicide","https://krushikendra.com/image/cache/catalog/Sygenta/syngenta-amistar-top-fungicides-500x500-800x800.jpg","https://krushikendra.com/Buy-Syngenta-Amistor-Top-Fungicide-100-ml-Online"),
(37,"V Bind Viral Disease Special","https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRmHRAqOUGXt76NPfOMXrUVRvDt8gRYd3-HTexGYI0d4PNmDuLXbfTchIRipVD-hx1wob7hHyVTbmyS85fTcADpBUMezetO&usqp=CAE","https://agribegri.com/products/viricide-online-.php"),
(38,"Tomato Fertilizer Organic","https://cdn.shopify.com/s/files/1/1489/8850/products/Tomato_feretilizer-new_869x868.jpg?v=1582699319","https://www.casagardenshop.com/products/tomato-fertilizer-for-home-terrace-outdoor-gardening"),
]

def main():
    data = {}
    for i, name, desc, prev, img in DISEASES:
        sup = next((s for s in SUPPLEMENTS if s[0] == i), (i, "", "", ""))
        data[str(i)] = {
            "index": i,
            "disease_name": name,
            "description": desc,
            "prevention": prev,
            "reference_image_url": img,
            "supplement_name": sup[1],
            "supplement_image": sup[2],
            "buy_link": sup[3],
        }
    out = os.path.join(os.path.dirname(__file__), "..", "data", "plant_data.json")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    print("Wrote", out, "entries:", len(data))

if __name__ == "__main__":
    main()
